baseURL = "https://hanneslink.github.io/hugo-test/"
RelativeURLs=true
CanonifyURLs=true
languageCode = "en-us"
title = "My New Hugo Site"
theme = "universal"
paginate = 10

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="blog"
    name = "Artikel"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url  = "/faq/"
    weight = 3

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "/contact/"
    weight = 4

# [Permalinks]
#     blog = "/blog/:year/:month/:day/:filename/"

[params]
    viewMorePostLink = "/blog/"
    mainSections = ["blog"]
    date_format = "January 2, 2006"
    latitude = "-12.043333"
    longitude = "-77.028333"
    direction = "Desamparados Station, Distrito de Lima 15001, Peru"
    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
    copyright = "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."
    address = """<p class="text-uppercase"><strong>Universal Ltd.</strong>
        <br>13/25 New Avenue
        <br>Newtown upon River
        <br>45Y 73J
        <br>England
        <br>
        <strong>Great Britain</strong>
      </p>
      """

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "This is just for testing. There will be some demo content in order to test the univeral theme. No need to worry"

