baseURL = "https://hanneslink.github.io/hugo-test/"
RelativeURLs=true
CanonifyURLs=true
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "This is just a test environment"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/HannesLink/hugo-test"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/CSIRO_ScienceImage_2042_A_row_of_computer_servers_in_a_server_rack.jpg"
  recent_posts_number = 2
